---

- name: perfSONAR Archive
  hosts:
    - ps_archive
  roles:
    - ansible-role-perfsonar-installer
  vars:
    perfsonar_bundle: perfsonar-archive
    perfsonar_optional_packages:
      - perfsonar-toolkit-security

- name: perfSONAR Testpoint
  hosts:
    - ps_testpoint
  roles:
    - ansible-role-perfsonar-installer
  vars:
    perfsonar_bundle: perfsonar-testpoint
    perfsonar_optional_packages:
      - perfsonar-toolkit-security

- name: perfSONAR Toolkit
  hosts:
    - ps_toolkit
  roles:
    - ansible-role-perfsonar-installer
  vars:
    perfsonar_bundle: perfsonar-toolkit
