---

- name: perfSONAR Archive
  hosts:
    - label_bundle_archive
  roles:
    - ansible-role-perfsonar-installer
  vars:
    perfsonar_bundle: perfsonar-archive

- name: perfSONAR Testpoint
  hosts:
    - label_bundle_testpoint
  roles:
    - ansible-role-perfsonar-installer
  vars:
    perfsonar_bundle: perfsonar-testpoint

- name: perfSONAR Toolkit
  hosts:
    - label_bundle_toolkit
  roles:
    - ansible-role-perfsonar-installer
  vars:
    perfsonar_bundle: perfsonar-toolkit
